name: lazy_cell
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/FabrizioG202/lazy_cell.git

environment:
  sdk: ">=3.0.0<4.0.0"

dev_dependencies:
  test:
  very_good_analysis:
